### ISSUE TITLE
iconv::open incorrect close if?

### ISSUE THREAD

**Issue by sinnren** [trueroad/iconv_wrapper#1]
inline void iconv::open (const std::string &fromcode,
                           const std::string &tocode)
  {
    if (convdesc == invalid_cd)   //?? ---> convdesc != invalid_cd  ???
      {
        close ();
      }
    convdesc = iconv_open (tocode.c_str (), fromcode.c_str ());
    if (convdesc == invalid_cd)
      {
        throw std::system_error (errno, std::system_category ());
      }
  }

**Comment by trueroad** [comment]
Fixed in https://github.com/trueroad/iconv_wrapper/commit/167e4d1695346242869b74a914f98e3df03f8b22 .
Thank you.
